### ISSUE TITLE
Is unlock working here?

### ISSUE THREAD

**Issue by e00dan** [classicalliu/gw-demos#6]
Is unlock example working in this repository? I'm working on similar implementation elsewhere using PortalWallet lock but can't make it work.

I see this repo is skipping `block_proof` in unlock function for witnessargs. Without it I get Error::InvalidArgs from withdrawLock (error code 4).

If I add block_proof ('0x') I get Error::ProofNotFound, error code 11

Here's my GodwokenWithdrawBuilder: https://github.com/jordanmack/ckb-tools/blob/63efb2259a050640d13d204c1a258d06f4724825/src/builders/GodwokenUnlockBuilder.ts

![image](https://user-images.githubusercontent.com/4950658/144329656-a446506b-b832-47d6-878b-949e337af527.png)

**Comment by classicalliu** [comment]
which `block_proof` in witness args ?

**Comment by e00dan** [comment]
> which `block_proof` in witness args ?

https://github.com/nervosnetwork/godwoken-examples/blob/develop/packages/tools/src/godwoken-cli.ts#L409 - is this needed @classicalliu?

**Comment by classicalliu** [comment]
> > which `block_proof` in witness args ?
> 
> https://github.com/nervosnetwork/godwoken-examples/blob/develop/packages/tools/src/godwoken-cli.ts#L409 - is this needed @classicalliu?

It's outdated.

https://github.com/nervosnetwork/godwoken/blob/v0.7.0-rc1/crates/types/schemas/godwoken.mol#L205-L206
`block_proof` has been removed.

If you need unlock, refer to this method
https://github.com/nervosnetwork/godwoken-examples/blob/develop/packages/tools/src/account/unlock.ts#L69

**Comment by e00dan** [comment]
@classicalliu 

Thank you for clarification. I figured out my problem. I was including StateValidator Cell Dep instead of latest Rollup Cell dependency (that changes once per minute).

Example unlock transaction showing funds nicely returning to Layer 1 account locked by Portal Wallet lock: https://explorer.nervos.org/aggron/transaction/0x13edfac8d9e13533db6b7939c6df54feede4904d4bd46834d77ff7b60687d7e2
